### ISSUE TITLE
转账确认页不该出现的错误提示

### ISSUE THREAD

**Issue by arisac** [arisac/metamask-extension#5]
1. Go to 'send', enter recipient address
2. Click on 'next' to confirm screen
3. `yellow exclamation mark` （string: "notCurrentAccount") displayed next to your from account. 

**Expected behavior**
正常使用转账时不该出现此提示，应为转换后地址的判断问题

**Comment by arisac** [comment]
@mengguang bug report

**Comment by mengguang** [comment]
fix mengguang/metamask-extension@d40a28df60127fa3fb23432602fad9a53858f6eb
