### ISSUE TITLE
交易详情交易费单位问题

### ISSUE THREAD

**Issue by arisac** [arisac/metamask-extension#6]
1. Go to 'Activity' Tab
2. Click on 'Any txn' to open Transaction Details window

交易详情交易费部分单位有 `ETH` 和 `GWEI` 未替换

- Activity Log 1
Gas Limit (Units)21000
Gas Used (Units)21000
Gas Price (G Isaac)21000

Transaction created with a value of 0.1 NEW at 2020-9-11 01:06.
Transaction submitted with gas fee of 0.441 **`ETH`** at 2020-9-11 01:06.
Transaction confirmed at 2020-9-11 01:06.

- Activity Log 2
Gas Limit (Units)21000
Gas Used (Units)21000
Gas Price (G Isaac)1

Transaction created with a value of 0 NEW at 2020-9-12 01:11.
Transaction submitted with gas fee of 21000 **`GWEI`** at 2020-9-12 06:00.
Transaction confirmed at 2020-9-12 06:00.

btw, 现在 Isaac 名称统一，不是 Issac，https://github.com/mengguang/metamask-extension/pull/4/commits/aef758ad18cec697bafee4935ad81e4947e9c093 i18n 中有修改

**Comment by arisac** [comment]
@mengguang bug report: gas fee unit in txn detail

**Comment by mengguang** [comment]
fixed  mengguang/metamask-extension@04d6303aba157886d82bbd4a20cff32a2cf39dd3
